# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-19 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    if settings.USE_I18N:

        operations = [
            migrations.CreateModel(
                name='CustomerRebate',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('percentage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Rebate in %')),
                    ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Groups')),
                    ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Customers')),
                ],
                options={
                    'db_table': 'shop_i18n_customerrebate',
                    'verbose_name': 'Customer Rebate', 'verbose_name_plural': 'Customer Rebates'
                },
                bases=(parler.models.TranslatableModelMixin, models.Model),
            ),
            migrations.CreateModel(
                name='CustomerRebateTranslation',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                    ('identifier', models.CharField(help_text='Rebate identifier will be shown on invoice', max_length=50, verbose_name='Identifier')),
                    ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shop_discounts.CustomerRebate')),
                ],
                options={
                    'db_table': 'shop_i18n_customerrebate_translation',
                },
            ),
            migrations.AlterUniqueTogether(
                name='customerrebatetranslation',
                unique_together=set([('language_code', 'master')]),
            ),
        ]

    else:

        operations = [
            migrations.CreateModel(
                name='CustomerRebate',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('percentage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Rebate in %')),
                    ('identifier', models.CharField(help_text='Rebate identifier will be shown on invoice', max_length=50, verbose_name='Identifier')),
                    ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Groups')),
                    ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Customers')),
                ],
                options={
                    'db_table': 'shop_customerrebate',
                    'verbose_name': 'Customer Rebate', 'verbose_name_plural': 'Customer Rebates'
                },
            ),
        ]
