# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, verbose_name='Identifier')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Rebate in %')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Groups')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Customers')),
            ],
            options={
                'db_table': 'shop_customerrebate',
                'verbose_name': 'Customer Rebate',
                'verbose_name_plural': 'Customer Rebates',
            },
        ),
    ]
